import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import type { Metadata } from "next";
import type { ReactNode } from "react";
import { cwd } from "node:process";
import { readdir, readFile } from "node:fs/promises";
import {
  SidebarProvider,
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
} from "@/components/ui/Sidebar";
import Link from "next/link";

import type { Crossword } from "@/types/crossword.types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type CrosswordMenuItem = {
  path: string;
  name: string;
};

async function getPuzzles(): Promise<CrosswordMenuItem[]> {
  const puzzleDirectory = `${cwd()}/crosswords`;
  let puzzleFiles = await readdir(puzzleDirectory);
  puzzleFiles = puzzleFiles.filter((puzzleFile) =>
    puzzleFile.endsWith(".json"),
  );

  const awaitingPuzles = puzzleFiles.map<Promise<CrosswordMenuItem>>(
    async (puzzleFile) => {
      const crossWordData: Crossword = JSON.parse(
        await readFile(`${puzzleDirectory}/${puzzleFile}`, {
          encoding: "utf8",
        }),
      );

      return {
        path: `/puzzle/${puzzleFile}`,
        name: crossWordData.title,
      };
    },
  );

  return Promise.all(awaitingPuzles);
}

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const puzzles = await getPuzzles();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <SidebarProvider open={true}>
          <div className="flex h-screen">
            <Sidebar>
              <SidebarContent>
                <SidebarGroup>
                  <SidebarGroupLabel>Available Puzzles</SidebarGroupLabel>
                  <SidebarGroupContent>
                    <SidebarMenu>
                      {puzzles.map((puzzle) => {
                        return (
                          <SidebarMenuItem
                            className="truncate capitalize"
                            key={puzzle.name}
                          >
                            <SidebarMenuButton asChild>
                              <Link href={puzzle.path}>
                                {puzzle.name.toLowerCase()}
                              </Link>
                            </SidebarMenuButton>
                          </SidebarMenuItem>
                        );
                      })}
                    </SidebarMenu>
                  </SidebarGroupContent>
                </SidebarGroup>
              </SidebarContent>
            </Sidebar>

            <main className="flex-1 overflow-y-auto">{children}</main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
